version: '3.1'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_DATABASE: delivery
    volumes:
      - ./database/install/mysql_init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
        - "3306:3306"
