name: CI

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: checkout push
          uses: actions/checkout@v2
        
        - name: Build Docker image
          run: docker build -t my-image .
 